{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "be647766-9e5e-46a3-be59-ac719d7aea2a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: requests in c:\\users\\ashab\\anaconda3\\lib\\site-packages (2.32.5)\n",
      "Requirement already satisfied: beautifulsoup4 in c:\\users\\ashab\\anaconda3\\lib\\site-packages (4.13.5)\n",
      "Requirement already satisfied: termcolor in c:\\users\\ashab\\anaconda3\\lib\\site-packages (3.3.0)\n",
      "Requirement already satisfied: tabulate in c:\\users\\ashab\\anaconda3\\lib\\site-packages (0.9.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\ashab\\anaconda3\\lib\\site-packages (from requests) (3.4.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\ashab\\anaconda3\\lib\\site-packages (from requests) (3.11)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\ashab\\anaconda3\\lib\\site-packages (from requests) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\ashab\\anaconda3\\lib\\site-packages (from requests) (2025.11.12)\n",
      "Requirement already satisfied: soupsieve>1.2 in c:\\users\\ashab\\anaconda3\\lib\\site-packages (from beautifulsoup4) (2.5)\n",
      "Requirement already satisfied: typing-extensions>=4.0.0 in c:\\users\\ashab\\anaconda3\\lib\\site-packages (from beautifulsoup4) (4.15.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "20 20 20\n",
      "1 The Handmaid’s Tale (The Handmaid's Tale, #1) - Margaret Atwood 4.15\n",
      "2 Anne of Green Gables (Anne of Green Gables, #1) - L.M. Montgomery 4.33\n",
      "3 Life of Pi - Yann Martel 3.94\n",
      "Total now: 21\n",
      "\n",
      "******************************************  Welcome to Books Organizer & Rating Calculator  **********************************************\n",
      "\n",
      "Menu:\n",
      "1 View Books\n",
      "2 Add Book\n",
      "3 View Reading List\n",
      "4 Reading Summary\n",
      "5 Statistics\n",
      "6 Highest Rated Book\n",
      "7 Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "\n",
      "Please select an option(1-7): 3\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Your reading list is Empty.\n",
      "Enter 2 to add books to your Reading List.\n",
      "\n",
      "******************************************  Welcome to Books Organizer & Rating Calculator  **********************************************\n",
      "\n",
      "Menu:\n",
      "1 View Books\n",
      "2 Add Book\n",
      "3 View Reading List\n",
      "4 Reading Summary\n",
      "5 Statistics\n",
      "6 Highest Rated Book\n",
      "7 Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "\n",
      "Please select an option(1-7): 2\n",
      "Enter a book number to add to the reading list:  abc\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Invalid Input. Please enter a number.\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter a book number to add to the reading list:  999\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Book number out of range, Please enter a valid number. \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter a book number to add to the reading list:  20\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Book added to the reading list.\n",
      "\n",
      "******************************************  Welcome to Books Organizer & Rating Calculator  **********************************************\n",
      "\n",
      "Menu:\n",
      "1 View Books\n",
      "2 Add Book\n",
      "3 View Reading List\n",
      "4 Reading Summary\n",
      "5 Statistics\n",
      "6 Highest Rated Book\n",
      "7 Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "\n",
      "Please select an option(1-7): 2\n",
      "Enter a book number to add to the reading list:  3\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Book added to the reading list.\n",
      "\n",
      "******************************************  Welcome to Books Organizer & Rating Calculator  **********************************************\n",
      "\n",
      "Menu:\n",
      "1 View Books\n",
      "2 Add Book\n",
      "3 View Reading List\n",
      "4 Reading Summary\n",
      "5 Statistics\n",
      "6 Highest Rated Book\n",
      "7 Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "\n",
      "Please select an option(1-7): 1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Available Books:\n",
      "No           Title                Author   Rating\n",
      "1 The Handmaid’s Tale (The Handmaid's Tale, #1) Margaret Atwood 4.15\n",
      "2 Anne of Green Gables (Anne of Green Gables, #1) L.M. Montgomery 4.33\n",
      "3 Life of Pi Yann Martel 3.94\n",
      "4 Water for Elephants Sara Gruen 4.11\n",
      "5 A Fine Balance Rohinton Mistry 4.38\n",
      "6 The English Patient Michael Ondaatje 3.86\n",
      "7 Fall on Your Knees Ann-Marie MacDonald 3.97\n",
      "8 Alias Grace Margaret Atwood 4.04\n",
      "9 Oryx and Crake (MaddAddam, #1) Margaret Atwood 4.0\n",
      "10 Fifth Business (The Deptford Trilogy, #1) Robertson Davies 4.06\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Do you want to see more books? (y/n):  n\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "******************************************  Welcome to Books Organizer & Rating Calculator  **********************************************\n",
      "\n",
      "Menu:\n",
      "1 View Books\n",
      "2 Add Book\n",
      "3 View Reading List\n",
      "4 Reading Summary\n",
      "5 Statistics\n",
      "6 Highest Rated Book\n",
      "7 Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "\n",
      "Please select an option(1-7): 3\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Your Reading List:\n",
      "\n",
      "YOUR BOOK YOUR AUTHOR None\n",
      "Water for Elephants Sara Gruen 4.11\n",
      "\n",
      "******************************************  Welcome to Books Organizer & Rating Calculator  **********************************************\n",
      "\n",
      "Menu:\n",
      "1 View Books\n",
      "2 Add Book\n",
      "3 View Reading List\n",
      "4 Reading Summary\n",
      "5 Statistics\n",
      "6 Highest Rated Book\n",
      "7 Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "\n",
      "Please select an option(1-7): 5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Average Rating:  4.11\n",
      "Median Rating:  4.11\n",
      "\n",
      "******************************************  Welcome to Books Organizer & Rating Calculator  **********************************************\n",
      "\n",
      "Menu:\n",
      "1 View Books\n",
      "2 Add Book\n",
      "3 View Reading List\n",
      "4 Reading Summary\n",
      "5 Statistics\n",
      "6 Highest Rated Book\n",
      "7 Exit\n"
     ]
    }
   ],
   "source": [
    "# CIND830 - Assignment1\n",
    "# Name: Abdullah Shaban\n",
    "# Student ID: 501456290\n",
    "\n",
    "\n",
    "# Purpose: Build a small, reliable Python prototype that collects real book data from the web, stores it\n",
    "# correctly, and produces readable summaries and statistics through an interactive menu \n",
    "\n",
    "# ************************************************************* Part 1 ***********************************************************************\n",
    "# -------------------------------------------------- Foundation (Data & Setup) ----------------------------------------------------------------\n",
    "\n",
    "# ------------------------------------------------ Task 1: Installing and Importing the Requried Libraries ----------------------------------------------\n",
    "\n",
    "%pip install requests beautifulsoup4 termcolor tabulate\n",
    "import re\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "from termcolor import colored\n",
    "from tabulate import tabulate\n",
    "\n",
    "URL = \"https://www.goodreads.com/list/show/2702.Best_Canadian_Literature\"\n",
    "HEADERS = {\"User-Agent\": \"Mozilla/5.0\"}\n",
    "\n",
    "# ---------------------------------------------- Task 2: Scrape top 20 into Parallel lists ------------------------------------------------------------\n",
    "\n",
    "try:\n",
    "    resp = requests.get(URL, headers=HEADERS, timeout=10)\n",
    "    resp.raise_for_status()\n",
    "except Exception as e:\n",
    "    print(colored(\"Could not download page. Check internet/URL.\", \"red\"))\n",
    "    print(\"Error:\", e)\n",
    "    raise\n",
    "    \n",
    "soup = BeautifulSoup(resp.text, \"html.parser\")\n",
    "\n",
    "table = soup.find(\"table\", class_=\"tableList\")\n",
    "if table is None:\n",
    "    print(colored(\"Could not find the books table (tableList). Page changed.\", \"red\"))\n",
    "    raise ValueError(\"Missing tableList\")\n",
    "    \n",
    "rows = table.find_all(\"tr\")[:20]\n",
    "\n",
    "titles, authors, ratings = [], [], []\n",
    "for row in rows:\n",
    "    t = row.find(\"a\", class_=\"bookTitle\")\n",
    "    a = row.find(\"a\", class_=\"authorName\")\n",
    "    m = row.find(\"span\", class_=\"minirating\")\n",
    "    \n",
    "    title = t.get_text(strip=True) if t else \"N/A\"\n",
    "    author = a.get_text(strip=True) if a else \"N/A\"\n",
    "    rating = None\n",
    "    if m:\n",
    "        match = re.search(r\"\\d+\\.\\d+\", m.get_text(strip=True))\n",
    "        if match:\n",
    "            rating = float(match.group())\n",
    "    titles.append(title)\n",
    "    authors.append(author)\n",
    "    ratings.append(rating)\n",
    "    \n",
    "print(len(titles), len(authors), len(ratings))\n",
    "\n",
    "for i in range(3):\n",
    "    print(i+1, titles[i], \"-\", authors[i], ratings[i])\n",
    "\n",
    "\n",
    "\n",
    "# ----------------------------------------------------- Task 3: Add one special book ---------------------------------------------------------------\n",
    "\n",
    "titles.append(\"YOUR BOOK\")\n",
    "authors.append(\"YOUR AUTHOR\")\n",
    "#Test case to show calculate stats with atleast one None Ratings\n",
    "ratings.append(None)\n",
    "print(\"Total now:\", len(titles))\n",
    "\n",
    "#  ********************************************************* End of Part 1 ************************************************************************\n",
    "\n",
    "# ************************************************************** Part 2 *****************************************************************************\n",
    "\n",
    "# ------------------------------------------------ Interactive Program (Menu + Features) -----------------------------------------------------------\n",
    "\n",
    "\n",
    "#initializing an empty list to store the indicies of selected books \n",
    "reading_index = [] \n",
    "\n",
    "#using a while loop to build a menu loop that runs until the user enters 6 i.e exit the loop/program \n",
    "\n",
    "while True:\n",
    "    print(\"\\n******************************************  Welcome to Books Organizer & Rating Calculator  **********************************************\")\n",
    "    print(\"\\nMenu:\")\n",
    "    print(\"1 View Books\")\n",
    "    print(\"2 Add Book\")\n",
    "    print(\"3 View Reading List\")\n",
    "    print(\"4 Reading Summary\")\n",
    "    print(\"5 Statistics\")\n",
    "    print(\"6 Highest Rated Book\")\n",
    "    print(\"7 Exit\")\n",
    "    \n",
    "    #Getting input from the user to make a selection\n",
    "    option = input(\"\\nPlease select an option(1-7):\")\n",
    "\n",
    "    #If user doesnot enter a digit, to prevent the program from crashing, asking user to enter numbers only\n",
    "    if option.isalpha():\n",
    "        print(\"Sorry! You can only enter Numbers.\")\n",
    "    #else if the input is a number then typecasting it to an int \n",
    "    elif option.isdigit():\n",
    "        option = int(option)\n",
    "        \n",
    "    #If user selects option 1 then show available books (upto 10 rows)\n",
    "    if option == 1:\n",
    "        print(\"\\nAvailable Books:\")\n",
    "        print(\"No\",  \"          Title           \", \"    Author \" ,   \" Rating\")\n",
    "\n",
    "        count = 0 \n",
    "\n",
    "        #using for loop to print all the available books \n",
    "        for i in range(len(titles)):\n",
    "            print(1+i, titles[i], authors[i], ratings[i])\n",
    "            count +=1\n",
    "\n",
    "            #Displaying only first 10 books by default then asking user if they want to see more books\n",
    "            if count == 10:\n",
    "                show_more= input(\"Do you want to see more books? (y/n): \").lower()\n",
    "\n",
    "                #If the user doesnot wants to see more books then break out of the loop, else reset value of count to 0 and show all the books \n",
    "                if show_more !='y':\n",
    "                    break\n",
    "                else:\n",
    "                    count = 0\n",
    "\n",
    "    #If user selects option 2 then Adding book to the Reading list \n",
    "    elif option ==2:\n",
    "        if len(titles) == 0:\n",
    "            print(\"No books available. \")\n",
    "            continue\n",
    "\n",
    "        #Validating user input\n",
    "        while True:\n",
    "            num = input(\"Enter a book number to add to the reading list: \")\n",
    "\n",
    "            #Input validation 1: if user enters anything other than a number display a warning!\n",
    "            if not num.isdigit():\n",
    "                print(\"Invalid Input. Please enter a number.\")\n",
    "                continue\n",
    "            \n",
    "            num = int(num)\n",
    "\n",
    "            #Input validation 2: Checking if the user is entering the correct/valid book number\n",
    "            if num<0 or num>=len(titles):\n",
    "                print(\"Book number out of range, Please enter a valid number. \")\n",
    "                continue\n",
    "\n",
    "            #Input validation 3: If user entered a book number that already exists in the reading list, print a warning!\n",
    "            if num in reading_index:\n",
    "                print(\"Book already in the reading list\")\n",
    "                continue\n",
    "\n",
    "            else:\n",
    "                break\n",
    "\n",
    "        #After input validation, add the book to the reading list\n",
    "        reading_index.append(num)\n",
    "        print(\"Book added to the reading list.\")\n",
    "\n",
    "\n",
    "    #If user selects option 3 then displaying the reading list\n",
    "    elif option ==3:\n",
    "\n",
    "        #Check if the reading list is empty \n",
    "        if len(reading_index)==0:\n",
    "            print(\"\\nYour reading list is Empty.\")\n",
    "            print(\"Enter 2 to add books to your Reading List.\")\n",
    "\n",
    "        #Display the Reading List\n",
    "        else:\n",
    "            print(\"\\nYour Reading List:\\n\")\n",
    "            #print(\"Title            Author               Ratings\")\n",
    "            \n",
    "            for index in reading_index:\n",
    "                print(titles[index], authors[index], ratings[index])\n",
    "        \n",
    "\n",
    "    \n",
    "    #If user selects Option 4\n",
    "    elif option ==4:\n",
    "        if len(reading_index) ==0:\n",
    "            print(\"Reading List is empty. \")\n",
    "            continue\n",
    "\n",
    "        summary_authors=[]\n",
    "        summary_counts=[]\n",
    "\n",
    "        for index in reading_index:\n",
    "            author = authors[index]\n",
    "\n",
    "            if author in summary_authors:\n",
    "                position = summary_authors.index(author)\n",
    "                summary_counts[position] +=1\n",
    "            else:\n",
    "                summary_authors.append(author)\n",
    "                summary_counts.append(1)\n",
    "\n",
    "        print(\"\\nBooks per Author\")\n",
    "        for i in range(len(summary_authors)):\n",
    "            print(summary_authors[i], \":\", summary_counts[i])\n",
    "\n",
    "    #If user selects option 5 \n",
    "    elif option == 5:\n",
    "        valid_ratings=[]\n",
    "\n",
    "        for index in reading_index:\n",
    "            if ratings[index] is not None:\n",
    "                valid_ratings.append(ratings[index])\n",
    "\n",
    "\n",
    "        if len(valid_ratings) ==0:\n",
    "            print(\"No Ratings Available.\")\n",
    "            continue\n",
    "\n",
    "        total=0\n",
    "        median=0\n",
    "\n",
    "        for rating in valid_ratings:\n",
    "            total += rating\n",
    "\n",
    "        avg = total/len(valid_ratings)\n",
    "\n",
    "        #sort the ratings is ascending order\n",
    "        valid_ratings.sort()\n",
    "        mid = len(valid_ratings)//2\n",
    "\n",
    "        #check if dataset is odd, then median is the middle value\n",
    "        if len(valid_ratings)%2 ==1:\n",
    "            median = valid_ratings[mid]\n",
    "        #else if dataset is even, then the median is average of middle value and the value before the mid value\n",
    "        else:\n",
    "            median= (valid_ratings[mid-1]+valid_ratings[mid])/2\n",
    "\n",
    "\n",
    "        print(\"Average Rating: \", round(avg,2))\n",
    "        print(\"Median Rating: \" , median)\n",
    "\n",
    "        \n",
    "                \n",
    "       \n",
    "    #If user selects Option 6 then show the Highest Rated Book from Reading List\n",
    "    #This feature improves usability by allowing staff to quickly identify the highest-rated book in a user’s reading list, \n",
    "    #making recommendations easier and reducing manual comparison efforts.\n",
    "    elif option==6:\n",
    "        #If the reading list is empty\n",
    "        if len(reading_index)==0:\n",
    "            print(\"Reading list is Empty.\")\n",
    "            continue\n",
    "\n",
    "        #Initialzing to save the maximum rating and index of \n",
    "        max_rating=0\n",
    "        max_index=0\n",
    "\n",
    "        for index in reading_index:\n",
    "            #Check if rating is not Empty\n",
    "            if ratings[index] is not None:\n",
    "                if max_rating==0 or ratings[index]>max_rating:\n",
    "                    max_rating=ratings[index]\n",
    "                    max_index=index\n",
    "        #If max rating is zero means No rated books in the list \n",
    "        if max_rating==0:\n",
    "            print(\"No rated books in the reading list.\")\n",
    "\n",
    "        #Else display the book with highest rating including titles, author name and the rating\n",
    "        else:\n",
    "            print(\"Highest Rated Book:\")\n",
    "            print(titles[max_index], \"-\",authors[max_index], \"Rating:\", ratings[max_index])\n",
    "                \n",
    "\n",
    "    \n",
    "    #End the program if user selects option 7       \n",
    "    elif option == 7:\n",
    "        print(\"******************************************************  Goodbye  *****************************************************************\")\n",
    "        break\n",
    "    #If user enters any other number othen than 1-7 then show them a warning message and again ask to enter the correct input.\n",
    "    else:\n",
    "        print(\"The Option you entered is not valid. Please enter 1-7.\")\n",
    "\n",
    "\n",
    "\n",
    "#********************************************************* This is the End of Program ***************************************************************\n",
    "        \n",
    "\n",
    "    \n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c96a608d-91e7-408d-af43-8836e9323751",
   "metadata": {},
   "source": [
    "Reflection on Work:\n",
    "\n",
    "1. Hardest Bug/Problem:\n",
    "   The hardest problem was safely handling user input without crashing the program. Initially, entering letters/alphabets instead of numbers caused       ValueError when converting input to int causing the program to crash. I fixed this by using .isalpha() and .isdigit() checks before conversion.\n",
    "\n",
    "   Another challenge was keeping all lists aligned when adding books to the reading list. Using a separate list of indices (reading_index) solved         this, because it avoided duplicating data and ensured titles, authors, and ratings always stayed in sync.\n",
    "\n",
    "\n",
    "2. Insights for a Non-Technical User:\n",
    "    From the Reading Summary/statistics, a non-technical user can easily understand their reading preferences. The summary shows which authors appear      most often, helping users see patterns in their interests.\n",
    "\n",
    "   The average and median ratings give a simple measure of overall quality, even when some books have no ratings. This helps users or staff make          informed decisions, such as which books to recommend or which authors a reader prefers most.\n",
    "\n",
    "\n",
    "3. Transferable Skills to Data Roles:\n",
    "   This assignment builds core data skills such as data validation, handling missing values such as None, working with lists, and calculating summary     statistics like average and median.\n",
    "\n",
    "   Looping through data, filtering values, and producing simple insights are fundamental tasks in data analysis and data engineering. The menu-driven     approach also strengthens logical thinking and defensive programming, which are important when working with real-world datasets that often contain     errors or incomplete information.\n",
    "\n",
    "\n",
    "4. AI Disclosure:\n",
    "    I used ChatGPT (GPT-5.2) for limited support: clarifying Python errors, validating logic, and improving explanations.\n",
    "\n",
    "   I wrote and reviewed the final code myself, tested all menu options manually, and verified that inputs, edge cases, and calculations worked            correctly without crashes.\n",
    "    \n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "635f88fb-631b-45e9-9c53-5542f59e749c",
   "metadata": {},
   "source": [
    "Required Tests:\n",
    "\n",
    "Please Note that the below output is copied/pasted after running the python program and doing the required tests. \n",
    "\n",
    "1. Add book with abc → prints warning, continues:\n",
    "   Output from Program ->\n",
    "   \n",
    "   ******************************************  Welcome to Books Organizer & Rating Calculator  **********************************************\n",
    "\n",
    "Menu:\n",
    "1 View Books\n",
    "2 Add Book\n",
    "3 View Reading List\n",
    "4 Reading Summary\n",
    "5 Statistics\n",
    "6 Highest Rated Book\n",
    "7 Exit\n",
    "******************************************  Please select an option(1-7): ******************************************************** 2\n",
    "Enter a book number to add to the reading list:  abc\n",
    "Invalid Input. Please enter a number.\n",
    "Enter a book number to add to the reading list:\n",
    "\n",
    "\n",
    "2. Add book with out-of-range number (e.g., 999) → warning, continues:\n",
    "  Enter a book number to add to the reading list:  999\n",
    "  Book number out of range, Please enter a valid number.\n",
    "Enter a book number to add to the reading list:\n",
    "\n",
    "3. View reading list before adding → friendly empty message\n",
    "\n",
    "******************************************  Welcome to Books Organizer & Rating Calculator  **********************************************\n",
    "\n",
    "Menu:\n",
    "1 View Books\n",
    "2 Add Book\n",
    "3 View Reading List\n",
    "4 Reading Summary\n",
    "5 Statistics\n",
    "6 Highest Rated Book\n",
    "7 Exit\n",
    "******************************************  Please select an option(1-7): ******************************************************** 3\n",
    "\n",
    "Your reading list is Empty.\n",
    "Enter 2 to add books to your Reading List.\n",
    "\n",
    "******************************************  Welcome to Books Organizer & Rating Calculator  **********************************************\n",
    "\n",
    "Menu:\n",
    "1 View Books\n",
    "2 Add Book\n",
    "3 View Reading List\n",
    "4 Reading Summary\n",
    "5 Statistics\n",
    "6 Highest Rated Book\n",
    "7 Exit\n",
    "******************************************  Please select an option(1-7): \n",
    "\n",
    "\n",
    "4. Stats when at least one selected rating is None → still computes using valid ratings\n",
    "   \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0d7e0c80-7c0d-412c-883f-04ebb58ddabe",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
